### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by jonathanchristison** [release-engineering/offliner#31]
I keep hitting the following error (with the default concurrent connection settings and reducing it down to 100) -

`    Download execution manager failed.
    java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
            at java.util.concurrent.FutureTask.report(FutureTask.java:122)
            at java.util.concurrent.FutureTask.get(FutureTask.java:192)
            at com.redhat.red.offliner.Main.run(Main.java:178)
            at com.redhat.red.offliner.Main.main(Main.java:134)
    Caused by: java.util.ConcurrentModificationException
            at java.util.AbstractList$Itr.remove(AbstractList.java:380)
            at java.util.AbstractList.removeRange(AbstractList.java:571)
            at java.util.AbstractList.clear(AbstractList.java:234)
            at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:102)
            at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
            at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
            at com.redhat.red.offliner.Main.lambda$newDownloader$2(Main.java:464)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
`

I haven't had a chance to look into this in any detail and it can be resolved by re ruining repeatedly, i guess we can either reduce the default connection limit or catch the exception and retry.

**Comment by jdcasey** [comment]
I'm sure it's a collection that needs to be synchronized. I'll take a look today, and try to get a fixed release out asap

**Comment by jdcasey** [comment]
@jonathanchristison See Offliner 1.3.
