### ISSUE TITLE
gzip incorrectly handled by offliner

### ISSUE THREAD

**Issue by jonathanchristison** [release-engineering/offliner#33]
### The problem 
Offliner is uncompressing gzip files and not altering the name to reflect this

### My guess
Offliner or one of its underlying libraries incorrectly handles `.gz` files. I'm guessing this is related to server optimisation and not recompressing gzip files where possible. However the offliner tool will decompress the gzip file as i presume it doesn't handle the gzip flag, it also fails due to the filename containing `.gz` or more likely based on the content-type - `Content-Type: application/x-gzip`

### Reproducer
```
wget http://X/brewroot/repos/jb-fuse-6.2-build/latest/maven/com/redhat/fuse/eap/fuse-eap/6.3.0.redhat-224/fuse-eap-6.3.0.redhat-224-project-sources.tar.gz

wget http://X/brewroot/repos/jb-fuse-6.2-build/latest/maven/io/fabric8/bom/fabric8-bom/1.2.0.redhat-630224/fabric8-bom-1.2.0.redhat-630224-project-sources.tar.gz
```

offliner pom - 
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>org.jboss.fuse.offline-maven-repo</groupId>
<artifactId>repo</artifactId>
<version>630224-mrrc</version>
<packaging>pom</packaging>
<name>Fuse 630224-mrrc Maven repository</name>
<dependencies>
    <dependency>
        <groupId>com.redhat.fuse.eap</groupId>
        <artifactId>fuse-eap</artifactId>
        <version>6.3.0.redhat-224</version>
        <type>tar.gz</type>
        <classifier>project-sources</classifier>
    </dependency>
    <dependency>
        <groupId>io.fabric8.bom</groupId>
        <artifactId>fabric8-bom</artifactId>
        <version>1.2.0.redhat-630224</version>
        <type>tar.gz</type>
        <classifier>project-sources</classifier>
    </dependency>
</dependencies>
<repositories>
    <repository>
        <id>ga</id>
        <url>http://maven.repository.redhat.com/ga/</url>
    </repository>
</repositories>
</project>
```

offliner invocation -
```
java -jar $st/offliner-1.3.jar -d gzip-test gzip-min.pom -r http://X/brewroot/repos/jb-fuse-6.2-build/latest/maven/
```

Which also gives errors for checksum files, which fail to download - 
```
Path: com/redhat/fuse/eap/fuse-eap/6.3.0.redhat-224/fuse-eap-6.3.0.redhat-224-project-sources.tar.gz.md5
---------------------------------------------------------------
java.io.IOException: URL: http://X/brewroot/repos/jb-fuse-6.2-build/latest/maven/com/redhat/fuse/eap/fuse-eap/6.3.0.redhat-224/fuse-eap-6.3.0.redhat-224-project-sources.tar.gz.md5 failed.
   at com.redhat.red.offliner.Main.lambda$newDownloader$2(Main.java:529)
   at com.redhat.red.offliner.Main$$Lambda$4/1776957250.call(Unknown Source)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.ZipException: Not in GZIP format
   at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
   at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
   at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
   at org.apache.http.client.protocol.ResponseContentEncoding$1.create(ResponseContentEncoding.java:67)
   at org.apache.http.client.entity.LazyDecompressingInputStream.initWrapper(LazyDecompressingInputStream.java:54)
   at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:66)
   at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
   at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
   at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
   at com.redhat.red.offliner.Main.lambda$newDownloader$2(Main.java:482)
   ... 7 more
```

and also results in uncompressed tars, which differs from the wget/curl tar.gz -
```
fabric8-bom-1.2.0.redhat-630224-project-sources.tar.gz: gzip compressed data, from FAT filesystem (MS-DOS, OS/2, NT)
gzip-test/io/fabric8/bom/fabric8-bom/1.2.0.redhat-630224/fabric8-bom-1.2.0.redhat-630224-project-sources.tar.gz: POSIX tar archive
```

**Comment by jonathanchristison** [comment]
Looking a bit more into the checksums the target http server in question is at fault, it incorrectly identifies `x.tar.gz.md5` `.x.tar.gz.sha` as  `Content-Type: application/x-gzip` so not really the offliners fault there, however i believe it is still at fault by trying to decode where Content-Type: application/x-gzip and `Content-Encoding: x-gzip` or maybe not rely on the response headers at all for content-type?

**Comment by chirino** [comment]
@jonathanchristison  What is '-r http://X/brewroot/repos/jb-fuse-6.2-build/latest/maven/'?  How can I reproduce?

**Comment by jdcasey** [comment]
@jonathanchristison I added a functional test to check this, and even tried the reproducer you mention above, without any luck. I suspect Apache httpclient might be a bit sensitive to misconfigured servers, and that the server has since been fixed for gzip / x-gzip content encoding.

It's odd; httpclient's response handlers cannot even SEE the Content-Encoding header, even though you can see the header going through over the wire if you have wire logging enabled. I'm not sure how to fix that, but it doesn't seem to matter...unless it's really fragile, in which case I suspect there's a httpclient piece that we might have to rewrite. It wouldn't be the first time. :(
